name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker Image
      run: |
        docker build -f Dockerfile.test -t odoo-test .

    - name: Start PostgreSQL
      run: |
        docker run -d --name postgres -e POSTGRES_DB=postgres -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo postgres:13

    - name: Start Odoo with Testing
      run: |
        docker run --name odoo-test --link postgres:db -d odoo-test

    - name: Execute Tests
      run: |
        # Insert the command to run your tests within the Odoo container
        docker exec odoo-test /path/to/your/test/script
